version: '3'

services:
  www:
    build: .
    environment:
      RUN_CROND: "true"
      GOGS_LDAP_HOST: openldap
      GOGS_LDAP_USER_BASE: dc=test,dc=hyperdev,dc=cloud
      GOGS_LDAP_BIND_DN: cn=readonly,dc=test,dc=hyperdev,dc=cloud
      GOGS_LDAP_BIND_PASSWORD: readonly
      GOGS_DOMAIN: gogs.test.hyperdev.cloud
    ports:
      - "3000:3000"
    volumes:
      - ./data/gogs:/data

  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: gogs
      POSTGRES_PASSWORD: gogs
    volumes:
      - data:/var/lib/postgresql/data

  openldap:
    image: osixia/openldap:1.1.10
    environment:
      - LDAP_ORGANISATION=test
      - LDAP_DOMAIN=test.hyperdev.cloud
      - LDAP_BASE_DN=dc=test,dc=hyperdev,dc=cloud
      - LDAP_ADMIN_PASSWORD=admin
      - LDAP_READONLY_USER=true
    command: --copy-service
    volumes:
      - ./users.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/50-bootstrap.ldif

  phpldapadmin:
    image: osixia/phpldapadmin:0.7.1
    depends_on:
      - openldap
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
    ports:
      - "8000:443"

volumes:
  data: {}
