version: 2
jobs:
  build:
    docker:
      - image: docker:18.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and push Docker image
          command: |
            docker build -t hyperdev/gogs .
            docker tag hyperdev/gogs hyperdev/gogs:$CIRCLE_TAG
            docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
            docker push hyperdev/gogs
            docker push hyperdev/gogs:$CIRCLE_TAG

workflows:
  version: 2
  tagged_build:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
